<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>5 Maps: coordinates, distances and neighbours | Relatives and Neighbours</title>
<meta name="author" content="Muhammad Rehan">
<meta name="description" content="Spatial models need one of two things from your coordinates: distances between languages, or a list of who neighbours whom. Build both, and learn what each choice assumes.  Fitted with sf,...">
<meta name="generator" content="bookdown 0.48 with bs4_book()">
<meta property="og:title" content="5 Maps: coordinates, distances and neighbours | Relatives and Neighbours">
<meta property="og:type" content="book">
<meta property="og:description" content="Spatial models need one of two things from your coordinates: distances between languages, or a list of who neighbours whom. Build both, and learn what each choice assumes.  Fitted with sf,...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="5 Maps: coordinates, distances and neighbours | Relatives and Neighbours">
<meta name="twitter:description" content="Spatial models need one of two things from your coordinates: distances between languages, or a list of who neighbours whom. Build both, and learn what each choice assumes.  Fitted with sf,...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.11.0/transition.js"></script><script src="libs/bs3compat-0.11.0/tabs.js"></script><script src="libs/bs3compat-0.11.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Modelling phylogenetic and spatial autocorrelation in cross-linguistic data, with R packages only">Relatives and Neighbours</a>:
        <small class="text-muted">Modelling phylogenetic and spatial autocorrelation in cross-linguistic data, with R packages only</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Welcome</a></li>
<li class="book-part">The problem</li>
<li><a class="" href="the-problem.html"><span class="header-section-number">1</span> Seeing the problem</a></li>
<li class="book-part">Phylogeny</li>
<li><a class="" href="trees.html"><span class="header-section-number">2</span> Trees: the raw material</a></li>
<li><a class="" href="phylogeny.html"><span class="header-section-number">3</span> Phylogeny as a covariance matrix</a></li>
<li><a class="" href="phylogeny-engines.html"><span class="header-section-number">4</span> Phylogeny in INLA, mgcv and by maximum likelihood</a></li>
<li class="book-part">Space</li>
<li><a class="active" href="maps.html"><span class="header-section-number">5</span> Maps: coordinates, distances and neighbours</a></li>
<li><a class="" href="space-surface.html"><span class="header-section-number">6</span> Space as a smooth surface</a></li>
<li><a class="" href="space-neighbours.html"><span class="header-section-number">7</span> Space as a network of neighbours</a></li>
<li><a class="" href="space-engines.html"><span class="header-section-number">8</span> Space in INLA, mgcv and by maximum likelihood</a></li>
<li class="book-part">Space and phylogeny</li>
<li><a class="" href="joint.html"><span class="header-section-number">9</span> Both at once</a></li>
<li><a class="" href="joint-engines.html"><span class="header-section-number">10</span> Both at once in INLA and mgcv</a></li>
<li><a class="" href="outcomes.html"><span class="header-section-number">11</span> Other kinds of outcome</a></li>
<li class="book-part">Sampling and simulation</li>
<li><a class="" href="sampling.html"><span class="header-section-number">12</span> Sampling instead of modelling</a></li>
<li><a class="" href="simulation.html"><span class="header-section-number">13</span> Does it recover the truth?</a></li>
<li class="book-part">Looking ahead</li>
<li><a class="" href="where-next.html"><span class="header-section-number">14</span> Where next</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="maps" class="section level1" number="5">
<h1>
<span class="header-section-number">5</span> Maps: coordinates, distances and neighbours<a class="anchor" aria-label="anchor" href="#maps"><i class="fas fa-link"></i></a>
</h1>
<p class="lede">
Spatial models need one of two things from your coordinates: distances between languages, or a list of who neighbours whom. Build both, and learn what each choice assumes.
</p>
<p class="chapter-meta">
<span><b>Fitted with</b> sf, spdep</span><span><b>Model fitting</b> about two minutes; the polygon section downloads 140 MB once</span><span><b>Packages</b> <code>sf</code> <code>spdep</code> <code>rnaturalearth</code> <code>ggplot2</code></span><span><a href="scripts/05-maps.R">Download the R script</a></span>
</p>
<div id="set-up-3" class="section level2" number="5.1">
<h2>
<span class="header-section-number">5.1</span> Set up<a class="anchor" aria-label="anchor" href="#set-up-3"><i class="fas fa-link"></i></a>
</h2>
<div class="sourceCode" id="cb108"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/">sf</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/r-spatial/spdep/">spdep</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://docs.ropensci.org/rnaturalearth/">rnaturalearth</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">base</span> <span class="op">&lt;-</span> <span class="st">"https://rehan-muh.github.io/tutorials/data/"</span></span>
<span><span class="va">d</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="va">base</span>, <span class="st">"languages.csv"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">d</span><span class="op">$</span><span class="va">elev_km</span> <span class="op">&lt;-</span> <span class="va">d</span><span class="op">$</span><span class="va">elevation</span> <span class="op">/</span> <span class="fl">1000</span></span></code></pre></div>
</div>
<div id="languages-as-points" class="section level2" number="5.2">
<h2>
<span class="header-section-number">5.2</span> Languages as points<a class="anchor" aria-label="anchor" href="#languages-as-points"><i class="fas fa-link"></i></a>
</h2>
<p>The data give each language one longitude and one latitude. <code><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf()</a></code> turns those two columns into a spatial object, and <code>crs = 4326</code> says they are ordinary degrees on the globe.</p>
<div class="sourceCode" id="cb109"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">pts</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf</a></span><span class="op">(</span><span class="va">d</span>, coords <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"lon"</span>, <span class="st">"lat"</span><span class="op">)</span>, crs <span class="op">=</span> <span class="fl">4326</span>, remove <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">pts</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"name"</span>, <span class="st">"family"</span>, <span class="st">"geometry"</span><span class="op">)</span><span class="op">]</span></span></code></pre></div>
<pre><code>## Simple feature collection with 3 features and 2 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: 36.7 ymin: 7.39 xmax: 39.3 ymax: 44
## Geodetic CRS:  WGS 84
##              name       family          geometry
## 1 West Circassian Abkhaz-Adyge   POINT (39.3 44)
## 2            Beja Afro-Asiatic POINT (36.7 17.2)
## 3  Alaba-K'abeena Afro-Asiatic POINT (38.2 7.39)</code></pre>
<p>A point is a simplification. A language is spoken over an area, sometimes a discontinuous one, and Glottolog’s point is roughly its centre. For a world sample that is good enough. For a study of one region, speaker-area polygons are better if you can get them, and the last section of this chapter shows where they plug in.</p>
</div>
<div id="distances" class="section level2" number="5.3">
<h2>
<span class="header-section-number">5.3</span> Distances<a class="anchor" aria-label="anchor" href="#distances"><i class="fas fa-link"></i></a>
</h2>
<p>Distance on a globe is measured along great circles. <code><a href="https://r-spatial.github.io/sf/reference/geos_measures.html">st_distance()</a></code> does it for <code>sf</code> points and <code><a href="https://edzer.github.io/sp/reference/spDistsN1.html">sp::spDists()</a></code> returns a plain matrix in kilometres, which is the more convenient form.</p>
<div class="sourceCode" id="cb111"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">coords</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span><span class="op">(</span><span class="va">d</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"lon"</span>, <span class="st">"lat"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="va">km</span> <span class="op">&lt;-</span> <span class="fu">sp</span><span class="fu">::</span><span class="fu"><a href="https://edzer.github.io/sp/reference/spDistsN1.html">spDists</a></span><span class="op">(</span><span class="va">coords</span>, longlat <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dimnames.html">dimnames</a></span><span class="op">(</span><span class="va">km</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">d</span><span class="op">$</span><span class="va">name</span>, <span class="va">d</span><span class="op">$</span><span class="va">name</span><span class="op">)</span></span>
<span></span>
<span><span class="va">show</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Tigrinya"</span>, <span class="st">"Harari"</span>, <span class="st">"Zulu"</span>, <span class="st">"Central Aymara"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">km</span><span class="op">[</span><span class="va">show</span>, <span class="va">show</span><span class="op">]</span><span class="op">)</span></span></code></pre></div>
<pre><code>##                Tigrinya Harari Zulu Central Aymara
## Tigrinya              0    753 4984          12318
## Harari              753      0 4417          12500
## Zulu               4984   4417    0           9929
## Central Aymara    12318  12500 9929              0</code></pre>
<p>Next, find how far each language is from its nearest neighbour in the sample.</p>
<div class="sourceCode" id="cb113"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">nearest</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">km</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="cn">Inf</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">km</span><span class="op">)</span><span class="op">)</span>, <span class="fl">1</span>, <span class="va">min</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">nearest</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   0%  25%  50%  75% 100% 
##    5   75  138  275 1508</code></pre>
<p>The sample is very uneven: half the languages have another within about 140 km, and the most isolated is 1,500 km from anything. Every spatial model has to cope with that, and they cope in different ways.</p>
</div>
<div id="flat-maps-and-their-cost" class="section level2" number="5.4">
<h2>
<span class="header-section-number">5.4</span> Flat maps and their cost<a class="anchor" aria-label="anchor" href="#flat-maps-and-their-cost"><i class="fas fa-link"></i></a>
</h2>
<p>Some models (the Gaussian process of Chapter <a href="space-surface.html#space-surface">6</a>) want coordinates in which ordinary straight-line distance means something. Degrees will not do: a degree of longitude is 111 km at the equator and 56 km at 60° north. The fix is to project. Equal Earth is a reasonable projection for the whole world.</p>
<div class="sourceCode" id="cb115"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">xy</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_coordinates.html">st_coordinates</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_transform.html">st_transform</a></span><span class="op">(</span><span class="va">pts</span>, <span class="st">"+proj=eqearth"</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fl">1000</span>   <span class="co"># km</span></span>
<span><span class="va">flat_km</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/dist.html">dist</a></span><span class="op">(</span><span class="va">xy</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">close</span> <span class="op">&lt;-</span> <span class="va">km</span> <span class="op">&lt;</span> <span class="fl">3000</span> <span class="op">&amp;</span> <span class="fu"><a href="https://rdrr.io/r/base/lower.tri.html">upper.tri</a></span><span class="op">(</span><span class="va">km</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">flat_km</span><span class="op">[</span><span class="va">close</span><span class="op">]</span> <span class="op">/</span> <span class="va">km</span><span class="op">[</span><span class="va">close</span><span class="op">]</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.05</span>, <span class="fl">0.5</span>, <span class="fl">0.95</span><span class="op">)</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   5%  50%  95% 
## 0.86 0.97 1.17</code></pre>
<p>For pairs of languages within 3,000 km, the distance on the flat map is mostly within about 15% of the true one. The error comes mostly at high latitudes and across the cut at the 180th meridian, where Alaska and Chukotka end up on opposite edges.</p>
<p>Methods that work on the sphere need no projection. They take either degrees directly or the position of each language as a point on a unit sphere:</p>
<div class="sourceCode" id="cb117"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">to_sphere</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">lon</span>, <span class="va">lat</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">rad</span> <span class="op">&lt;-</span> <span class="va">pi</span> <span class="op">/</span> <span class="fl">180</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Trig.html">cos</a></span><span class="op">(</span><span class="va">lat</span> <span class="op">*</span> <span class="va">rad</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/Trig.html">cos</a></span><span class="op">(</span><span class="va">lon</span> <span class="op">*</span> <span class="va">rad</span><span class="op">)</span>,</span>
<span>        y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Trig.html">cos</a></span><span class="op">(</span><span class="va">lat</span> <span class="op">*</span> <span class="va">rad</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/Trig.html">sin</a></span><span class="op">(</span><span class="va">lon</span> <span class="op">*</span> <span class="va">rad</span><span class="op">)</span>,</span>
<span>        z <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Trig.html">sin</a></span><span class="op">(</span><span class="va">lat</span> <span class="op">*</span> <span class="va">rad</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu">to_sphere</span><span class="op">(</span><span class="va">d</span><span class="op">$</span><span class="va">lon</span>, <span class="va">d</span><span class="op">$</span><span class="va">lat</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span></span></code></pre></div>
<pre><code>##          x     y     z
## [1,] 0.556 0.456 0.695
## [2,] 0.766 0.570 0.296
## [3,] 0.780 0.613 0.129</code></pre>
</div>
<div id="neighbours" class="section level2" number="5.5">
<h2>
<span class="header-section-number">5.5</span> Neighbours<a class="anchor" aria-label="anchor" href="#neighbours"><i class="fas fa-link"></i></a>
</h2>
<p>The other family of models (Chapter <a href="space-neighbours.html#space-neighbours">7</a>) never looks at a distance. It needs a graph that says which languages count as neighbours. For points there is no natural answer, so you choose a rule. Three common ones:</p>
<div class="sourceCode" id="cb119"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 1. the k nearest languages, made mutual</span></span>
<span><span class="va">knn</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/spdep/reference/testnb.html">make.sym.nb</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/spdep/reference/knn2nb.html">knn2nb</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/spdep/reference/knearneigh.html">knearneigh</a></span><span class="op">(</span><span class="va">coords</span>, k <span class="op">=</span> <span class="fl">5</span>, longlat <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 2. every language within a fixed distance</span></span>
<span><span class="va">band</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/spdep/reference/dnearneigh.html">dnearneigh</a></span><span class="op">(</span><span class="va">coords</span>, <span class="fl">0</span>, <span class="fl">500</span>, longlat <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 3. natural neighbours: a triangulation of the points</span></span>
<span><span class="va">tri</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/spdep/reference/tri2nb.html">tri2nb</a></span><span class="op">(</span><span class="va">coords</span><span class="op">)</span></span>
<span></span>
<span><span class="va">compare</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">nb</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>links_per_language <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/spdep/reference/card.html">card</a></span><span class="op">(</span><span class="va">nb</span><span class="op">)</span><span class="op">)</span>, <span class="fl">1</span><span class="op">)</span>,</span>
<span>    without_neighbours <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/spdep/reference/card.html">card</a></span><span class="op">(</span><span class="va">nb</span><span class="op">)</span> <span class="op">==</span> <span class="fl">0</span><span class="op">)</span>,</span>
<span>    separate_pieces    <span class="op">=</span> <span class="fu"><a href="https://r-spatial.github.io/spdep/reference/compon.html">n.comp.nb</a></span><span class="op">(</span><span class="va">nb</span><span class="op">)</span><span class="op">$</span><span class="va">nc</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="st">"5 nearest"</span> <span class="op">=</span> <span class="fu">compare</span><span class="op">(</span><span class="va">knn</span><span class="op">)</span>, <span class="st">"within 500 km"</span> <span class="op">=</span> <span class="fu">compare</span><span class="op">(</span><span class="va">band</span><span class="op">)</span>,</span>
<span>      <span class="st">"triangulation"</span> <span class="op">=</span> <span class="fu">compare</span><span class="op">(</span><span class="va">tri</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##               links_per_language without_neighbours separate_pieces
## 5 nearest                    6.4                  0               1
## within 500 km                9.1                 44              85
## triangulation                6.0                  0               1</code></pre>
<p>Read the three columns as three things that can go wrong.</p>
<ul>
<li>Nearest neighbours give every language about the same number of links, whether its neighbours are 20 km away or 2,000. The graph is in one piece.</li>
<li>A distance band is the most natural idea and the most troublesome in a world sample. Languages in dense regions get dozens of links, isolated ones get none, and the graph falls into many pieces. The models of Chapter <a href="space-neighbours.html#space-neighbours">7</a> need one piece.</li>
<li>A triangulation always gives one piece and needs no tuning. It also draws long links across oceans, and because it works on raw degrees it treats the map as flat.</li>
</ul>
<div class="sourceCode" id="cb121"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">world</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://docs.ropensci.org/rnaturalearth/reference/ne_countries.html">ne_countries</a></span><span class="op">(</span>scale <span class="op">=</span> <span class="st">"small"</span>, returnclass <span class="op">=</span> <span class="st">"sf"</span><span class="op">)</span></span>
<span><span class="va">wrap</span>  <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">nb</span><span class="op">)</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_transform.html">st_wrap_dateline</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/spdep/reference/nb2lines.html">nb2lines</a></span><span class="op">(</span><span class="va">nb</span>, coords <span class="op">=</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html">st_geometry</a></span><span class="op">(</span><span class="va">pts</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                                       options <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"WRAPDATELINE=YES"</span>,</span>
<span>                                                   <span class="st">"DATELINEOFFSET=60"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">world</span>, fill <span class="op">=</span> <span class="st">"grey94"</span>, colour <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu">wrap</span><span class="op">(</span><span class="va">knn</span><span class="op">)</span>, colour <span class="op">=</span> <span class="st">"#2A78D6"</span>, linewidth <span class="op">=</span> <span class="fl">0.25</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu">wrap</span><span class="op">(</span><span class="va">band</span><span class="op">)</span>, colour <span class="op">=</span> <span class="st">"#EB6834"</span>, linewidth <span class="op">=</span> <span class="fl">0.2</span>, alpha <span class="op">=</span> <span class="fl">0.6</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">pts</span>, size <span class="op">=</span> <span class="fl">0.4</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">coord_sf</a></span><span class="op">(</span>crs <span class="op">=</span> <span class="st">"+proj=eqearth"</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:maps-graph-map"></span>
<span id="fig:maps-graph-map" style="display:block;"></span>
<img src="figures/05-maps/graph-map-1.png" alt="Two neighbour graphs on the same languages: the five nearest (blue) and everything within 500 km (orange). The distance band leaves much of the world unconnected." width="710"><p class="caption">
Figure 5.1: Two neighbour graphs on the same languages: the five nearest (blue) and everything within 500 km (orange). The distance band leaves much of the world unconnected.
</p>
</div>
<blockquote>
<p><strong>Watch out.</strong> No rule knows any linguistics. A link across the Sahara counts the same as a link between neighbouring villages, and two languages on either side of a mountain range are neighbours if they are close on the map. You can edit a graph by hand with <code><a href="https://r-spatial.github.io/spdep/reference/edit.nb.html">edit.nb()</a></code>, or build it from a table of known contact. Whatever you do, draw it, and try the analysis with a second graph.</p>
</blockquote>
</div>
<div id="from-a-graph-to-weights" class="section level2" number="5.6">
<h2>
<span class="header-section-number">5.6</span> From a graph to weights<a class="anchor" aria-label="anchor" href="#from-a-graph-to-weights"><i class="fas fa-link"></i></a>
</h2>
<p>Models use the graph as a matrix. There are two conventions and they are not interchangeable.</p>
<div class="sourceCode" id="cb122"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">W_binary</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/spdep/reference/nb2mat.html">nb2mat</a></span><span class="op">(</span><span class="va">knn</span>, style <span class="op">=</span> <span class="st">"B"</span><span class="op">)</span>   <span class="co"># 1 for a neighbour, 0 otherwise</span></span>
<span><span class="va">W_rows</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/spdep/reference/nb2mat.html">nb2mat</a></span><span class="op">(</span><span class="va">knn</span>, style <span class="op">=</span> <span class="st">"W"</span><span class="op">)</span>   <span class="co"># each row divided by its row sum</span></span>
<span></span>
<span><span class="va">W_binary</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">4</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">4</span><span class="op">]</span></span></code></pre></div>
<pre><code>##   1 2 3 4
## 1 0 0 0 0
## 2 0 0 0 0
## 3 0 0 0 1
## 4 0 0 1 0</code></pre>
<div class="sourceCode" id="cb124"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/Matrix/man/colSums-methods.html">rowSums</a></span><span class="op">(</span><span class="va">W_rows</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">4</span><span class="op">]</span>, <span class="fl">2</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 1 2 3 4 
## 1 1 1 1</code></pre>
<p>The binary matrix is what the conditional autoregressive models of Chapter <a href="space-neighbours.html#space-neighbours">7</a> take. The row-standardised one, usually stored as a list with <code><a href="https://r-spatial.github.io/spdep/reference/nb2listw.html">nb2listw()</a></code>, is what Moran’s I and the simultaneous autoregressive models of Chapter <a href="space-engines.html#space-engines">8</a> take. With row standardisation a language’s neighbours always sum to one, so a language with two neighbours listens to each of them more than a language with ten.</p>
</div>
<div id="how-far-does-similarity-reach" class="section level2" number="5.7">
<h2>
<span class="header-section-number">5.7</span> How far does similarity reach?<a class="anchor" aria-label="anchor" href="#how-far-does-similarity-reach"><i class="fas fa-link"></i></a>
</h2>
<p>Chapter <a href="the-problem.html#the-problem">1</a> computed Moran’s I for immediate neighbours. A correlogram repeats the calculation for neighbours of neighbours, and theirs, and so on, which shows how quickly similarity fades with graph distance.</p>
<div class="sourceCode" id="cb126"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">m0</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">ejectives</span> <span class="op">~</span> <span class="va">elev_km</span>, family <span class="op">=</span> <span class="va">binomial</span>, data <span class="op">=</span> <span class="va">d</span><span class="op">)</span></span>
<span><span class="va">res</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">m0</span>, type <span class="op">=</span> <span class="st">"pearson"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">cg</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/spdep/reference/sp.correlogram.html">sp.correlogram</a></span><span class="op">(</span><span class="va">knn</span>, <span class="va">res</span>, order <span class="op">=</span> <span class="fl">6</span>, method <span class="op">=</span> <span class="st">"I"</span>, style <span class="op">=</span> <span class="st">"W"</span><span class="op">)</span></span>
<span><span class="va">steps</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>step <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">6</span>, I <span class="op">=</span> <span class="va">cg</span><span class="op">$</span><span class="va">res</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>, se <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">cg</span><span class="op">$</span><span class="va">res</span><span class="op">[</span>, <span class="fl">3</span><span class="op">]</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">steps</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">step</span>, <span class="va">I</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, linetype <span class="op">=</span> <span class="st">"22"</span>, colour <span class="op">=</span> <span class="st">"grey35"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_linerange</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin <span class="op">=</span> <span class="va">I</span> <span class="op">-</span> <span class="fl">2</span> <span class="op">*</span> <span class="va">se</span>, ymax <span class="op">=</span> <span class="va">I</span> <span class="op">+</span> <span class="fl">2</span> <span class="op">*</span> <span class="va">se</span><span class="op">)</span>,</span>
<span>                 colour <span class="op">=</span> <span class="st">"#2A78D6"</span>, linewidth <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="st">"#2A78D6"</span>, size <span class="op">=</span> <span class="fl">2.6</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">6</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"steps apart on the neighbour graph"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Moran's I of the residuals"</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:maps-correlogram"></span>
<span id="fig:maps-correlogram" style="display:block;"></span>
<img src="figures/05-maps/correlogram-1.png" alt="Moran's I of the naive model's residuals for neighbours one to six steps apart on the five-nearest-neighbour graph, with two standard errors either side. Similarity is strongest between direct neighbours and is still present several steps away." width="710"><p class="caption">
Figure 5.2: Moran’s I of the naive model’s residuals for neighbours one to six steps apart on the five-nearest-neighbour graph, with two standard errors either side. Similarity is strongest between direct neighbours and is still present several steps away.
</p>
</div>
<p>A correlogram that dies out within a step or two says that a neighbour model will capture the dependence. One that stays high for many steps, as here, says the patterns are regional, and a model with a smooth surface or a long reach is the better description.</p>
<blockquote>
<p><strong>With your own data.</strong> If your units are areas, read the polygons with <code><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read()</a></code> and call <code><a href="https://r-spatial.github.io/spdep/reference/poly2nb.html">poly2nb()</a></code> to link areas that share a border; everything from <code>nb</code> onward is the same. If your sample covers one region, project to a local system (a UTM zone, or an equal-area projection centred on your region) and the flat-map error all but disappears.</p>
</blockquote>
</div>
<div id="where-locations-come-from" class="section level2" number="5.8">
<h2>
<span class="header-section-number">5.8</span> Where locations come from<a class="anchor" aria-label="anchor" href="#where-locations-come-from"><i class="fas fa-link"></i></a>
</h2>
<p>The coordinates in this book are Glottolog’s. They are the usual choice, and there are others.</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="33%">
<col width="33%">
<col width="33%">
</colgroup>
<thead><tr class="header">
<th align="left">Source</th>
<th align="left">What it gives</th>
<th align="left">How to get it</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">Glottolog <span class="citation">(<a href="references.html#ref-glottolog">Hammarström et al., n.d.</a>)</span>
</td>
<td align="left">One point per language</td>
<td align="left">
<code>languages.csv</code> in its CLDF release; the <code>lingtypology</code> package <span class="citation">(<a href="references.html#ref-moroz2017">Moroz 2017</a>)</span>
</td>
</tr>
<tr class="even">
<td align="left">WALS, Grambank, PHOIBLE and other CLDF datasets</td>
<td align="left">The same points, shipped with the data</td>
<td align="left">The <code>languages.csv</code> of each dataset</td>
</tr>
<tr class="odd">
<td align="left">Glottography <span class="citation">(<a href="references.html#ref-glottography">Glottography, n.d.</a>)</span>
</td>
<td align="left">Speaker-area polygons digitised from published atlases and matched to Glottocodes</td>
<td align="left">The <code>Rglottography</code> package, or the GeoJSON files directly</td>
</tr>
<tr class="even">
<td align="left">Ethnologue <span class="citation">(<a href="references.html#ref-ethnologue">Eberhard et al. 2023</a>)</span>
</td>
<td align="left">Polygons for most languages</td>
<td align="left">Under licence only</td>
</tr>
<tr class="odd">
<td align="left">Glottolog, AUTOTYP <span class="citation">(<a href="references.html#ref-autotyp2023">Bickel et al. 2023</a>)</span>, WALS</td>
<td align="left">Areas as categories: macroareas and continental areas</td>
<td align="left">A column in each database</td>
</tr>
</tbody>
</table></div>
<p>Glottography is the open source of polygons. Its largest dataset digitises the <em>Atlas of the World’s Languages</em> <span class="citation">(<a href="references.html#ref-asher2007">Asher and Moseley 2007</a>)</span> and comes in two layers, the areas where languages are spoken now and the areas where they were spoken traditionally. Its other datasets cover single regions and families in more detail.</p>
</div>
<div id="speaker-areas-as-polygons" class="section level2" number="5.9">
<h2>
<span class="header-section-number">5.9</span> Speaker areas as polygons<a class="anchor" aria-label="anchor" href="#speaker-areas-as-polygons"><i class="fas fa-link"></i></a>
</h2>
<p>Read the contemporary layer of the atlas. The file is about 90 MB, so this takes a minute the first time.</p>
<div class="sourceCode" id="cb127"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">src</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"https://raw.githubusercontent.com/Glottography/"</span>,</span>
<span>                <span class="st">"asher2007world/v2.0/cldf/"</span><span class="op">)</span></span>
<span><span class="va">areas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="va">src</span>, <span class="st">"contemporary/languages.geojson"</span><span class="op">)</span>, quiet <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">areas</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">areas</span><span class="op">)</span> <span class="op">==</span> <span class="st">"cldf.languageReference"</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="st">"glottocode"</span></span>
<span></span>
<span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/s2.html">sf_use_s2</a></span><span class="op">(</span><span class="cn">FALSE</span><span class="op">)</span>                  <span class="co"># repair the shapes on the flat map</span></span>
<span><span class="va">areas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/valid.html">st_make_valid</a></span><span class="op">(</span><span class="va">areas</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">areas</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 4062</code></pre>
<p>Each row is one language with its area, possibly in several pieces. Match the areas to the sample by Glottocode.</p>
<div class="sourceCode" id="cb129"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">has</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sets.html">intersect</a></span><span class="op">(</span><span class="va">d</span><span class="op">$</span><span class="va">glottocode</span>, <span class="va">areas</span><span class="op">$</span><span class="va">glottocode</span><span class="op">)</span></span>
<span><span class="va">mine</span> <span class="op">&lt;-</span> <span class="va">areas</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/match.html">match</a></span><span class="op">(</span><span class="va">has</span>, <span class="va">areas</span><span class="op">$</span><span class="va">glottocode</span><span class="op">)</span>, <span class="op">]</span></span>
<span><span class="va">here</span> <span class="op">&lt;-</span> <span class="va">pts</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/match.html">match</a></span><span class="op">(</span><span class="va">has</span>, <span class="va">pts</span><span class="op">$</span><span class="va">glottocode</span><span class="op">)</span>, <span class="op">]</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>sample <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">d</span><span class="op">)</span>, with_an_area <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">has</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##       sample with_an_area 
##          500          310</code></pre>
<div class="sourceCode" id="cb131"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/s2.html">sf_use_s2</a></span><span class="op">(</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">km2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/geos_measures.html">st_area</a></span><span class="op">(</span><span class="va">mine</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fl">1e6</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">km2</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##      0%     25%     50%     75%    100% 
##      25     842    3712   17604 2467678</code></pre>
<p>Now ask how far each Glottolog point is from the area the atlas gives the same language. A distance of zero means the point is inside.</p>
<div class="sourceCode" id="cb133"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">gap</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/geos_measures.html">st_distance</a></span><span class="op">(</span><span class="va">here</span>, <span class="va">mine</span>, by_element <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fl">1000</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>inside <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">gap</span> <span class="op">==</span> <span class="fl">0</span><span class="op">)</span>, outside <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">gap</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  inside outside 
##     172     138</code></pre>
<div class="sourceCode" id="cb135"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">gap</span><span class="op">[</span><span class="va">gap</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">]</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="fl">0.9</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  50%  90% 100% 
##   18  142 1063</code></pre>
<div class="sourceCode" id="cb137"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/s2.html">sf_use_s2</a></span><span class="op">(</span><span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">box</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_bbox.html">st_bbox</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>xmin <span class="op">=</span> <span class="fl">32</span>, ymin <span class="op">=</span> <span class="fl">2</span>, xmax <span class="op">=</span> <span class="fl">49</span>, ymax <span class="op">=</span> <span class="fl">19</span><span class="op">)</span>, crs <span class="op">=</span> <span class="fl">4326</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crop.html">st_crop</a></span><span class="op">(</span><span class="va">world</span>, <span class="va">box</span><span class="op">)</span>, fill <span class="op">=</span> <span class="st">"grey94"</span>, colour <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crop.html">st_crop</a></span><span class="op">(</span><span class="va">areas</span>, <span class="va">box</span><span class="op">)</span>, fill <span class="op">=</span> <span class="st">"#2A78D6"</span>, alpha <span class="op">=</span> <span class="fl">0.1</span>,</span>
<span>          colour <span class="op">=</span> <span class="st">"#2A78D6"</span>, linewidth <span class="op">=</span> <span class="fl">0.2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crop.html">st_crop</a></span><span class="op">(</span><span class="va">pts</span>, <span class="va">box</span><span class="op">)</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">ejectives</span><span class="op">)</span><span class="op">)</span>,</span>
<span>          shape <span class="op">=</span> <span class="fl">21</span>, size <span class="op">=</span> <span class="fl">2.2</span>, stroke <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"0"</span> <span class="op">=</span> <span class="st">"white"</span>, <span class="st">"1"</span> <span class="op">=</span> <span class="st">"#EB6834"</span><span class="op">)</span>,</span>
<span>                    labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"no ejectives"</span>, <span class="st">"ejectives"</span><span class="op">)</span>, name <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:maps-areas-map"></span>
<span id="fig:maps-areas-map" style="display:block;"></span>
<img src="figures/05-maps/areas-map-1.png" alt="Speaker areas from the atlas (blue) around the Horn of Africa, with the Glottolog points of the sample languages on top. Filled points have ejectives. The areas differ enormously in size, some land (grey) has no area at all, and each language is still a single point." width="614"><p class="caption">
Figure 5.3: Speaker areas from the atlas (blue) around the Horn of Africa, with the Glottolog points of the sample languages on top. Filled points have ejectives. The areas differ enormously in size, some land (grey) has no area at all, and each language is still a single point.
</p>
</div>
<p>With polygons, neighbours can be defined as areas that touch. <code><a href="https://r-spatial.github.io/spdep/reference/poly2nb.html">poly2nb()</a></code> builds that graph.</p>
<div class="sourceCode" id="cb138"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">touching</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/spdep/reference/poly2nb.html">poly2nb</a></span><span class="op">(</span><span class="va">mine</span>, snap <span class="op">=</span> <span class="fl">0.01</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>links_per_language <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/spdep/reference/card.html">card</a></span><span class="op">(</span><span class="va">touching</span><span class="op">)</span><span class="op">)</span>, <span class="fl">1</span><span class="op">)</span>,</span>
<span>  without_neighbours <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/spdep/reference/card.html">card</a></span><span class="op">(</span><span class="va">touching</span><span class="op">)</span> <span class="op">==</span> <span class="fl">0</span><span class="op">)</span>,</span>
<span>  separate_pieces    <span class="op">=</span> <span class="fu"><a href="https://r-spatial.github.io/spdep/reference/compon.html">n.comp.nb</a></span><span class="op">(</span><span class="va">touching</span><span class="op">)</span><span class="op">$</span><span class="va">nc</span><span class="op">)</span></span></code></pre></div>
<pre><code>## links_per_language without_neighbours    separate_pieces 
##                0.9              161.0              194.0</code></pre>
<p>The graph is nearly empty, and the reason is the sample. Two languages of the sample touch only if no unsampled language lies between them, and 500 languages out of several thousand rarely do. A contiguity graph is meaningful when you have every language of a region. For a sample, link by distance or by nearest neighbours, as above.</p>
<p>The atlas has a second layer with traditional areas. Compare the centre of each language’s area in the two layers.</p>
<div class="sourceCode" id="cb140"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">past</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="va">src</span>, <span class="st">"traditional/languages.geojson"</span><span class="op">)</span>, quiet <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">past</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">past</span><span class="op">)</span> <span class="op">==</span> <span class="st">"cldf.languageReference"</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="st">"glottocode"</span></span>
<span><span class="va">past</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/valid.html">st_make_valid</a></span><span class="op">(</span><span class="va">past</span><span class="op">)</span></span>
<span></span>
<span><span class="va">both</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sets.html">intersect</a></span><span class="op">(</span><span class="va">mine</span><span class="op">$</span><span class="va">glottocode</span>, <span class="va">past</span><span class="op">$</span><span class="va">glottocode</span><span class="op">)</span></span>
<span><span class="va">centre_now</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/geos_unary.html">st_centroid</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html">st_geometry</a></span><span class="op">(</span><span class="va">mine</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/match.html">match</a></span><span class="op">(</span><span class="va">both</span>, <span class="va">mine</span><span class="op">$</span><span class="va">glottocode</span><span class="op">)</span>, <span class="op">]</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">centre_past</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/geos_unary.html">st_centroid</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html">st_geometry</a></span><span class="op">(</span><span class="va">past</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/match.html">match</a></span><span class="op">(</span><span class="va">both</span>, <span class="va">past</span><span class="op">$</span><span class="va">glottocode</span><span class="op">)</span>, <span class="op">]</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/s2.html">sf_use_s2</a></span><span class="op">(</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">moved</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/geos_measures.html">st_distance</a></span><span class="op">(</span><span class="va">centre_now</span>, <span class="va">centre_past</span>, by_element <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">moved</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">moved</span><span class="op">)</span> <span class="op">/</span> <span class="fl">1000</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>languages <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">both</span><span class="op">)</span>, moved_over_100_km <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">moved</span> <span class="op">&gt;</span> <span class="fl">100</span><span class="op">)</span>,</span>
<span>  furthest_km <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">moved</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##         languages moved_over_100_km       furthest_km 
##               294                26              4185</code></pre>
</div>
<div id="what-a-location-leaves-out" class="section level2" number="5.10">
<h2>
<span class="header-section-number">5.10</span> What a location leaves out<a class="anchor" aria-label="anchor" href="#what-a-location-leaves-out"><i class="fas fa-link"></i></a>
</h2>
<p>The numbers above are specific to this sample, and each points at a general problem.</p>
<p>A point stands for an area. The areas of the sample languages run from 25 to 2,467,678 square kilometres, and a single point represents each of them equally. Where two sources can be compared, they disagree: 138 of the 310 Glottolog points fall outside the area the atlas draws for the same language, half of those by more than 18 km and one by 1,063 km.</p>
<p>Coverage is incomplete. The atlas has a contemporary area for 310 of the 500 languages. A method that needs polygons would lose the rest, and the languages it loses are not a random subset: extinct and recently displaced languages are the ones without a present-day area.</p>
<p>A location has a date. 26 of the 294 languages with both layers moved by more than 100 km between their traditional and their present area, and the furthest by 4,185 km. If a feature arose before a language moved, the place where its speakers live now is the wrong place to look for its neighbours or its climate. Glottolog’s points do not say which period they describe.</p>
<p>A covariate measured at a point inherits all of this. The elevation in this book is the height of the ground at the Glottolog point. A language whose area runs from a coast to a plateau has no single elevation, and the point may sit at either end. With polygons you can take the mean or the range of elevation over the area, for example with <code><a href="https://rspatial.github.io/terra/reference/extract.html">terra::extract()</a></code>, and with points you cannot.</p>
<p>Distance is not contact. Great-circle distance ignores mountain ranges, seas, rivers and trade routes, and every model in the next three chapters treats 300 km across a desert like 300 km along a coast. The barrier models cited in Chapter <a href="space-engines.html#space-engines">8</a> are one response. Another is to compute distances that follow the terrain and to build the spatial matrix from those.</p>
<p>Drawn areas do not overlap, and languages do. An atlas gives each patch of ground to one language. Multilingual regions, cities, and languages of wider communication laid over local ones are not represented, though they are where much contact happens.</p>
<p>The map shows where linguists have worked. The sample is dense where description is dense. Two languages can be neighbours in the data because the languages between them have not been described, and a neighbour graph or a distance matrix will not show the difference.</p>
<p>Areas as categories have borders that somebody chose. Whether a language of the Caucasus belongs to Europe or to Asia changes which languages it is compared with, and the choice is a convention <span class="citation">(<a href="references.html#ref-hammarstrom2014">Hammarström and Donohue 2014</a>)</span>. Results that depend on where such a line is drawn are a known hazard of all analyses of areal units.</p>
<p>None of this argues against spatial models. It argues for saying where your locations come from and what period they describe, and for trying a second representation when one is available.</p>
</div>
<div id="what-to-carry-forward-4" class="section level2" number="5.11">
<h2>
<span class="header-section-number">5.11</span> What to carry forward<a class="anchor" aria-label="anchor" href="#what-to-carry-forward-4"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li>Great-circle distances come from <code>sp::spDists(coords, longlat = TRUE)</code>; projected coordinates from <code><a href="https://r-spatial.github.io/sf/reference/st_transform.html">st_transform()</a></code>; points on the sphere from three lines of trigonometry.</li>
<li>A neighbour graph depends on the rule you choose. Check <code><a href="https://r-spatial.github.io/spdep/reference/compon.html">n.comp.nb()</a></code> for pieces and <code><a href="https://r-spatial.github.io/spdep/reference/card.html">card()</a></code> for languages left alone, and draw the graph.</li>
<li>Binary weights go to CAR models; row-standardised weights go to Moran’s I and SAR models.</li>
<li>A correlogram tells you how far the dependence reaches before you choose a model for it.</li>
</ul>
</div>
<div id="further-reading-5" class="section level2" number="5.12">
<h2>
<span class="header-section-number">5.12</span> Further reading<a class="anchor" aria-label="anchor" href="#further-reading-5"><i class="fas fa-link"></i></a>
</h2>
<p><strong>How earlier studies represented space.</strong> For most of typology’s history, space meant a small number of large areas. <span class="citation">Dryer (<a href="references.html#ref-dryer1989">1989</a>)</span> divides the world into five (later six) continental areas and requires a pattern to hold in each; <span class="citation">Jaeger et al. (<a href="references.html#ref-jaeger2011">2011</a>)</span> make the same idea a random intercept for area beside the one for family. The step from areas to coordinates came later. <span class="citation">Wieling et al. (<a href="references.html#ref-wieling2011">2011</a>)</span> fit a smooth function of longitude and latitude in a GAM for Dutch dialect data. <span class="citation">Guzmán Naranjo and Becker (<a href="references.html#ref-guzman2022">2022</a>)</span> use a Gaussian process over coordinates for world samples, and <span class="citation"><span class="nocase">Skirgård et al.</span> (<a href="references.html#ref-skirgard2023">2023</a>)</span> build a spatial covariance matrix from great-circle distances with a Matérn kernel. <span class="citation">Ranacher et al. (<a href="references.html#ref-ranacher2021">2021</a>)</span> go the other way and infer discrete contact areas from the data.</p>
<ul>
<li>Glottography <span class="citation">(<a href="references.html#ref-glottography">Glottography, n.d.</a>)</span> documents its datasets and the atlases behind them; the two layers of the world atlas come from <span class="citation">Asher and Moseley (<a href="references.html#ref-asher2007">2007</a>)</span>.</li>
<li>
<span class="citation">Hammarström and Donohue (<a href="references.html#ref-hammarstrom2014">2014</a>)</span> set out how macro-areas should and should not be used in typological comparison.</li>
<li>
<span class="citation">Bivand et al. (<a href="references.html#ref-bivand2013">2013</a>)</span> is the standard account of spatial objects, neighbours and weights in R, by the authors of <code>spdep</code>.</li>
<li>
<span class="citation"><span class="nocase">Dormann et al.</span> (<a href="references.html#ref-dormann2007">2007</a>)</span> review how to account for spatial autocorrelation in regression, with a comparison of methods that maps closely onto the chapters that follow.</li>
<li>
<span class="citation">Banerjee et al. (<a href="references.html#ref-banerjee2014">2014</a>)</span> give the statistical theory behind both views of space, as a continuous surface and as a graph of areas.</li>
</ul>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="phylogeny-engines.html"><span class="header-section-number">4</span> Phylogeny in INLA, mgcv and by maximum likelihood</a></div>
<div class="next"><a href="space-surface.html"><span class="header-section-number">6</span> Space as a smooth surface</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#maps"><span class="header-section-number">5</span> Maps: coordinates, distances and neighbours</a></li>
<li><a class="nav-link" href="#set-up-3"><span class="header-section-number">5.1</span> Set up</a></li>
<li><a class="nav-link" href="#languages-as-points"><span class="header-section-number">5.2</span> Languages as points</a></li>
<li><a class="nav-link" href="#distances"><span class="header-section-number">5.3</span> Distances</a></li>
<li><a class="nav-link" href="#flat-maps-and-their-cost"><span class="header-section-number">5.4</span> Flat maps and their cost</a></li>
<li><a class="nav-link" href="#neighbours"><span class="header-section-number">5.5</span> Neighbours</a></li>
<li><a class="nav-link" href="#from-a-graph-to-weights"><span class="header-section-number">5.6</span> From a graph to weights</a></li>
<li><a class="nav-link" href="#how-far-does-similarity-reach"><span class="header-section-number">5.7</span> How far does similarity reach?</a></li>
<li><a class="nav-link" href="#where-locations-come-from"><span class="header-section-number">5.8</span> Where locations come from</a></li>
<li><a class="nav-link" href="#speaker-areas-as-polygons"><span class="header-section-number">5.9</span> Speaker areas as polygons</a></li>
<li><a class="nav-link" href="#what-a-location-leaves-out"><span class="header-section-number">5.10</span> What a location leaves out</a></li>
<li><a class="nav-link" href="#what-to-carry-forward-4"><span class="header-section-number">5.11</span> What to carry forward</a></li>
<li><a class="nav-link" href="#further-reading-5"><span class="header-section-number">5.12</span> Further reading</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Relatives and Neighbours</strong>: Modelling phylogenetic and spatial autocorrelation in cross-linguistic data, with R packages only" was written by Muhammad Rehan. </p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
